### ISSUE TITLE
ResourceExhaustedError [OOM] when runing  train_gpu.py

### ISSUE THREAD

**Issue by SuMarsss** [zihangdai/xlnet#125]
When I run train_gpu.py , I got ResourceExhaustedError

> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[512,1408,2,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
>          [[node model/transformer/layer_17/rel_attn/einsum_5/transpose_2 (defined at /data/wss/nlp/xlnet_extension_tf/xlnet/modeling.py:136) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
> 

> [[node model/transformer/StopGradient_18 (defined at /data/wss/nlp/xlnet_extension_tf/xlnet/modeling.py:201) ]]
> Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

So how do I change my parameter to avoid `ResourceExhaustedError ` and below is my params.
```
python train_gpu.py \
  --record_info_dir=data/tfrecords \
  --model_dir=data \
  --train_batch_size=2 \
  --seq_len=512 \
  --reuse_len=256 \
  --mem_len=30 \
  --perm_size=256 \
  --n_layer=24 \
  --d_model=1024 \
  --d_embed=1024 \
  --n_head=16 \
  --d_head=64 \
  --d_inner=4096 \
  --untie_r=True \
  --mask_alpha=6 \
  --mask_beta=1 \
  --num_predict=85 \
  --uncased=True \
  --num_core_per_host=1
```

**Comment by GeetDsa** [comment]
You can reduce the `train_batch_size` to 1, which would further degrade the performance, you can consider reducing `seq_len`.

**Comment by aditya-malte** [comment]
Hello @SuMarsss ,
It looks like you are running out of memory.
Try using my modified repo with the colab_imdb_tpu.ipynd that uses free Colab TPUs and can run with batch size 32 and seq_len = 256

https://github.com/aditya-malte/Colab-XLNet-FineTuning/blob/master/notebooks/colab_imdb_gpu.ipynb

**Comment by SuMarsss** [comment]
> Hello @SuMarsss ,
> It looks like you are running out of memory.
> Try using my modified repo with the colab_imdb_tpu.ipynd that uses free Colab TPUs and can run with batch size 32 and seq_len = 256
> 
> https://github.com/aditya-malte/Colab-XLNet-FineTuning/blob/master/notebooks/colab_imdb_gpu.ipynb

It sounds great and thanks a lot. I just fixed the [Out Of Memory] issue with smaller seq_len and lager batch_size yesterday, but I will try the free Colab TPUs you said.
