### ISSUE TITLE
Out of memory with TPU v3-8 when running tpu_squad_large.sh

### ISSUE THREAD

**Issue by lukemelas** [zihangdai/xlnet#15]
Hello, thank you for the interesting paper and for releasing your code alongside the paper! 

I am trying to train XL-Net on Squad, but I am getting OOM errors when running `scripts/tpu_squad_large.sh`. This strikes me as odd, because you say in the README that you can run this script without issues. I have not modified the parameters of the script, except for specifying the necessary data/model directories. 

For context, my setup is as follows. I spun up a TPU v3-8 using `ctpu up` in the `us-central1-a` region. I preprocessed the data as directed, using `scripts/prepro_squad.sh`, and moved to a Google Storage bucket in the same region as the TPU. I have model checkpoint folders both locally (for sentencepiece) and in the cloud (for loading the model). 

I have worked with TPUs before, but only TPU-v2 (not v3); is there something I am doing incorrectly? 

When I run `scripts/tpu_squad_large.sh`, loading and initialization work fine, but the script breaks with what I believe is a memory issue: 

```
# ... normal tensorflow logs ...

I0621 17:53:36.702727 140612788254144 tpu_estimator.py:536] Enqueue next (1000) batch(es) of data to infeed.
I0621 17:53:36.703403 140612788254144 tpu_estimator.py:540] Dequeue next (1000) batch(es) of data from outfeed.
I0621 17:56:15.833373 140611248187136 error_handling.py:70] Error recorded from outfeed: Bad hardware status: 0x1

# ... stack trace ...

Status code: Resource exhausted [9x]
  Compilation failure: Ran out of memory in memory space hbm. Used 20.90G of 16.00G hbm. Exceeded hbm capacity by 4.90G.

  Total hbm usage >= 20.90G:
      reserved        528.00M
      program          20.38G
      arguments       unknown size

  Output size unknown.
```

Is there something I am doing incorrectly? 

Also, have others managed to run `scripts/tpu_squad_large.sh` successfully (with batch size 48, etc.)?

**Comment by erichare** [comment]
I can confirm I get exactly the same error as you, with the same configuration and steps.

**Comment by lukemelas** [comment]
Thanks for the confirmation @erichare , good to know it's not an isolated issue.

**Comment by zihangdai** [comment]
Could you provide the environment you are in? I tested this script myself on cloud TPU 4 days ago without a problem.

**Comment by lukemelas** [comment]
Thank you for the quick and detailed response! 

I was using a TPU v3-8 with version 1.13, rather than 1.14.1.dev20190518. I have switched to a TPU with version 1.14.1.dev20190518 and it is currently training without the error. I will update this thread and close the issue when the script finishes and I am able to fully reproduce the Squad results. 

Thank you again!

**Comment by renatoviolin** [comment]
Could you share the train chekpoints for squad 2.0? 

Currently I'm fine tunning the large model, just training the last 7 layers (17, 18... 23) so that it can run in my hardware (RTX 2080 8GB), with a seq_length 340, batch_size 8, and FP_16.
I've already used this configuration with BERT-Large, and achieved F1-Score of 81.9.

With XLNet, up to now, the F1 Scores are ~ 81.5 for 30.000 train steps, which corresponds to ~ 2 epochs

Thank you for share the code and all needed details.

**Comment by zihangdai** [comment]
While sharing a pretrained ckpt is easy, it does not actually solve the training problem. I think the problem could be relieved if gradient accumulated is enabled. As a matter of fact, using the provided setting, training for 2000 steps should give you an F1 over 83. We'll think about this for more.

**Comment by lukemelas** [comment]
Update: the script finished running and everything worked properly. I got an F1 of 87.64 on the dev set, which is consistent with the results reported in the README (slightly lower than reported, but within the range of normal variation). 

Yes, @renatoviolin, I can certainly share the checkpoint file if you would like. As @zihangdai mentioned, however, it doesn't really solve the training problem. 

And @zihangdai, thank you again for your assistance! I am closing this issue.

**Comment by zihangdai** [comment]
@lukemelas We missed a feature which was added a few hours ago. If you use the updated code, the F1 should almost definitely be higher than 88.3 (the minimum I got based on the released ckpt out of 10 runs). Please let me know if you get a chance to rerun it.

**Comment by lukemelas** [comment]
Got it, I will pull from master and begin re-running now! I'll update you when it finishes.

**Comment by lukemelas** [comment]
Update: finished running script again, this time got F1 of 88.46. Looking good!

**Comment by renatoviolin** [comment]
@lukemelas have you tried to replace the single FC layer to a more deep layers at end of the network?
I already did this using BERT-Base and achieved ~3% increase in F1-Score, just replacing the last 1 FC layer to a 3 FC layer to predict start/end logits.  Hidden Size (768 -> 384 -> 192 )

Right now I'm doing the same with XLNet to see if it improves. In my case I'm only training the layers 17, 18, 19 ... 23) due my hardware limitations.

Maybe you could try this in your setup.

By the way, could you share you checkpoint?

**Comment by lukemelas** [comment]
Great idea, @renatoviolin. I'm away from my computer at the moment, but I will try adding the FC layers and also share the checkpoint when I return to lab tonight!

**Comment by lovedavidsilva** [comment]
@lukemelas I am having the same issue here. How did you get the TPU software configured to the version 1.14.1.dev20190518? I did not find a way to config it when starting the TPU or switch it after. Thanks.

**Comment by lukemelas** [comment]
Hi @lovedavidsilva, I don't think there's a way to change the TPU version once it's been created. You're going to have to delete it and create a new one.

**Comment by lovedavidsilva** [comment]
Thanks @lukemelas, when creating a new TPU, is it possible to specify the TPU software version? I can configure TPU size to v3-8, but the software version is still 1.13.

BTW, I am a United fan, but David Silva is my favorite :)

**Comment by lukemelas** [comment]
Here are some screenshots: 
https://ibb.co/ZB0jKkc
https://ibb.co/QpcYwhR

**Comment by ymcui** [comment]
@lovedavidsilva  alternatively, you can specify `--tf-version 1.14.1.dev20190518` when starting up TPU with `ctpu` utility.
An example:
```
ctpu up --name your-xlnet-tpu --tpu-size v3-8 --tpu-only --tf-version 1.14.1.dev20190518 --zone us-central1-b
``

**Comment by lovedavidsilva** [comment]
Thanks @lukemelas @ymcui, I'm not seeing OOM error now. How long does the training take?

**Comment by ymcui** [comment]
@lovedavidsilva  For me, it tooks ~2 hours on TPU v3-8 with default settings `batch_size=48, train_steps=8000, max_seq_length=512`. Note that, this does not include pre-processing time for SQuAD data.

**Comment by lovedavidsilva** [comment]
@ymcui I am still facing some issues with the training...

The terminal freezes at this stage and stops showing any further info:
`I0703 22:41:32.000724 140659050755520 tpu_estimator.py:536] Enqueue next (1000) batch(es) of data to infeed.`
`I0703 22:41:32.001449 140659050755520 tpu_estimator.py:540] Dequeue next (1000) batch(es) of data from outfeed.`

I check the output folder and there are checkpoints 0 and 1000.

The way I use the TPU is first creating one with the desired tf-version as you mentioned in the example, then using the default VM from "ctpu up --tpu-size v3-8" to clone the GitHub repository and run the SQuAD training. I have also finished the preprocessing and saved the output in my Bucket. Not sure if I did anything wrong here since I usually just use the default v2-8 TPU for BERT...

Do you mind sharing how you got everything done (especially the VM/local setup)?

Thanks!

**Comment by ymcui** [comment]
@lovedavidsilva As there is no error message shown in your log, it is quite hard to see what the actual problem is. Also, note that, there is nothing special for you to change from TPU v2 to v3.
1. Just use your VM that was used for BERT (nothing should be changed)
2. Set up TPU v3
```
ctpu up --name your-xlnet-tpu --tpu-size v3-8 --tpu-only --tf-version 1.14.1.dev20190518 --zone us-central1-b
```
3. Run your SQuAD training script.

Next: 
1. Maybe you need to set a smaller `train_steps` (say `20`) for quick debugging. Especially the error message by TensorFlow.
2. Post your shell script here to see if there is anything wrong with your settings.
3. Check your TensorFlow version (`pip list | grep tensorflow`) on VM to see if it is satisfy the requirements by XLNet.

**Comment by lovedavidsilva** [comment]
@ymcui I just used `--train_steps=6000` and it worked. Got best_f1 at 88.53. I think the performance loss is minimum according to the earlier posting from the author. Will use this checkpoint for further work. 

Thanks for your help!

**Comment by rusiaaman** [comment]
@zihangdai Is there a solution to this issue for colab TPU? We don't have control over the TPU software version (do we?) and I get the same error as this  (Error recorded from outfeed: Bad hardware status: 0x1) when working with tensorflow==1.13.1. 

Note that  TPU code works fine for `run_classifier` when used with tensorflow==1.14.0 BUT NOT with tensorflow==1.13.1 in which case the above mentioned error occurs. Now using tf==1.14.0 is fine for `run_classifier` but not for `train.py` pre-training which is dependent on tf==1.13.1 because of some code in `tpu_estimator.py` (error: no module named tensorflow.contrib.tpu.proto for tf==1.14.0)

I guess customer `tpu_estimator.py` was written to for handling `train_cache_fn` and `eval_cache_fn` not possible with default TPUEstimator, am I right? Can you think of work around for this so that I can work with pretraining on Colab TPU? 

> Could you provide the environment you are in? I tested this script myself on cloud TPU 4 days ago without a problem.
> #### An update: I just tried 30s ago. It works OK with the following set up.
> 
>     * TPU v3-8 software version (shown in Compute Engine -> TPUs): 1.14.1.dev20190518
> 
>     * Tensorflow version (the one you chose when launching a VM): 1.13.1
> 
> 
> Please let me know whether it works.
